import React from 'react';
import type { ContentCredentials } from '../../../core/types.js';
import { CheckIcon, ImageIcon, SparklesIcon } from '../icons/Icons.js';
import { PrimaryButton } from '../primitives/PrimaryButton.js';
import { SecondaryButton } from '../primitives/SecondaryButton.js';
import styles from './ContentCredentialsPanel.module.css';

interface ContentCredentialsPanelProps {
  credentials: ContentCredentials;
  previewUrl?: string;
  fileName?: string;
  onSelectAnother: () => void;
  onBackHome: () => void;
}

// IPTC digital source types in plain words
const SOURCE_TYPES: Record<string, string> = {
  trainedAlgorithmicMedia: 'AI-generated (trained model)',
  compositeWithTrainedAlgorithmicMedia: 'Edited with AI (contains AI-generated parts)',
  algorithmicMedia: 'Computer-generated (no AI model)',
  digitalCapture: 'Camera capture',
  computationalCapture: 'Camera capture (computational)',
  compositeCapture: 'Composite of photos',
  composite: 'Composite',
  digitalArt: 'Digital art',
  virtualRecording: 'Screen or virtual recording',
};

function formatDate(iso: string | undefined): string | undefined {
  if (!iso) return undefined;
  const date = new Date(iso);
  return Number.isNaN(date.getTime())
    ? iso
    : date.toLocaleString(undefined, { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
}

/**
 * Result for images with a provenance label but no generation metadata, e.g. from
 * ChatGPT or Gemini: they mark images as AI-generated but never store the prompt.
 */
export const ContentCredentialsPanel: React.FC<ContentCredentialsPanelProps> = ({
  credentials,
  previewUrl,
  fileName,
  onSelectAnother,
  onBackHome,
}) => {
  const { aiGenerated, product } = credentials;
  const partlyAi = /^compositeWithTrainedAlgorithmicMedia$/i.test(credentials.digitalSourceType ?? '');
  const rows: Array<[string, string | undefined]> = [
    ['Made with', product],
    ['Model / tool', credentials.softwareAgent !== product ? credentials.softwareAgent : undefined],
    ['Created', formatDate(credentials.created)],
    ['Label written by', credentials.claimGenerator],
    ['Signed by', credentials.signedBy],
    ['Source type', credentials.digitalSourceType && (SOURCE_TYPES[credentials.digitalSourceType] ?? credentials.digitalSourceType)],
    ['Label', credentials.source === 'c2pa' ? 'C2PA Content Credentials' : 'IPTC / XMP metadata'],
  ];

  return (
    <div className={styles.panel}>
      <div className={styles.imageCol}>
        {previewUrl ? (
          <img src={previewUrl} alt={fileName || 'Analyzed image'} className={styles.image} />
        ) : (
          <div className={styles.imagePlaceholder}>
            <ImageIcon size={28} />
          </div>
        )}
        {fileName && <div className={styles.fileName}>{fileName}</div>}
      </div>

      <div className={styles.infoCol}>
        <div className={aiGenerated ? styles.badgeAi : styles.badgeNeutral}>
          {aiGenerated ? <CheckIcon size={14} /> : <SparklesIcon size={14} />}
          {aiGenerated ? (partlyAi ? 'Confirmed AI-edited image' : 'Confirmed AI-generated image') : 'Content Credentials found'}
        </div>

        <h2 className={styles.title}>
          {aiGenerated ? (product ? `Made with ${product}` : 'AI-Generated Image') : 'No AI Label in This Image'}
        </h2>

        <p className={styles.lead}>
          {aiGenerated
            ? `The image carries a label from its creator saying it was ${partlyAi ? 'edited with' : 'generated by'} AI. No prompt or generation settings are available: services like ChatGPT and Gemini label their images but do not save the prompt in the file.`
            : 'The image has Content Credentials (for example from a camera or photo editor), but they do not mark it as AI-generated, and it contains no prompt or generation settings.'}
        </p>

        <dl className={styles.details}>
          {rows
            .filter(([, value]) => value)
            .map(([label, value]) => (
              <div key={label} className={styles.detailRow}>
                <dt>{label}</dt>
                <dd>{value}</dd>
              </div>
            ))}
        </dl>

        <p className={styles.note}>
          Shown as written in the file; PromptHound does not verify the label's digital signature. Screenshots and
          social media uploads usually remove this label.
        </p>

        <div className={styles.actions}>
          <PrimaryButton onClick={onSelectAnother}>
            <ImageIcon size={16} /> Select Another Image
          </PrimaryButton>
          <SecondaryButton onClick={onBackHome}>Back to Home</SecondaryButton>
        </div>
      </div>
    </div>
  );
};
